### ISSUE TITLE
Incident @ 12:00 (25/01/2024)

### ISSUE THREAD

**Issue by Ciarands** [Ciarands/vidsrc-keys#2]
`TypeError: Cannot read properties of null (reading '1')
    at patchEmbedJS (file:///app/index.mjs:89:73)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///app/index.mjs:121:30
    at async CdpHTTPRequest.finalizeInterceptions (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/HTTPRequest.js:83:9)`

**Comment by Ciarands** [comment]
Fixed @ 12:28

Appolgies for downtime, fixed edgecase with `patchEmbedJs` failing to fetch key function identifier in some callback cases, will monitor further.
